apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-conf
data:
  telegraf.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = "0s"
    [[inputs.exec]]
      commands = ["/usr/local/bin/script.sh"]
      timeout = "5s"
      data_format = "prometheus"
    [[outputs.prometheus_client]]
      listen = "0.0.0.0:9125"
  script.sh: |
    #!/bin/env bash

    timestamp=$(date +%s)
    echo "test_timestamp $timestamp"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: telegraf
  name: telegraf
  namespace: default
spec:
  containers:
  - image: telegraf
    name: telegraf
#    command: ["/bin/sleep"]
#    args:
#      - "1000"
    volumeMounts:
    - name: telegraf-conf
      mountPath: "/etc/telegraf/telegraf.conf"
      subPath: telegraf.conf
    - name: telegraf-conf
      mountPath: "/usr/local/bin/script.sh"
      subPath: script.sh
  volumes:
  - name: telegraf-conf
    configMap:
      name: telegraf-conf
      defaultMode: 0755
