apiVersion: v1
kind: Namespace
metadata:
  name: earth
---
apiVersion: v1
kind: Namespace
metadata:
  name: moon
---
apiVersion: v1
data:
  astronaut: YXJtc3Ryb25n
kind: Secret
metadata:
  name: pilot
  namespace: earth
