#---
#apiVersion: management.cattle.io/v3
#kind: User
#metadata:
#  name: m-voyager
#username: voyager
#enabled: true
#principalIds:
#- local://m-voyager
#password: "voyagervoyager"
---
# Attribution du rôle "Standard User"
apiVersion: management.cattle.io/v3
kind: GlobalRoleBinding
metadata:
  name: grb-voyager-standard-user
globalRoleName: user 
userName: m-nbfmx
---
apiVersion: management.cattle.io/v3
kind: ClusterRoleTemplateBinding
metadata:
  name: crtb-voyager-andromeda
  namespace: c-m-pqj5fs72
clusterName: c-m-pqj5fs72
roleTemplateName: cluster-member 
userName: m-nbfmx
---
apiVersion: management.cattle.io/v3
kind: ClusterRoleTemplateBinding
metadata:
  name: crtb-voyager-phoenix
  namespace: c-m-rmxcntlp
clusterName: c-m-rmxcntlp
roleTemplateName: cluster-member 
userName: m-nbfmx
