apiVersion: v1
kind: Secret
metadata:
  name: rancher-api-credentials
  namespace: default
type: Opaque
stringData:
  RANCHER_TOKEN: "token-vg6ds:99m67fc7c4dnpbj5zv5wflwgdj5wwvzt7xkv75r9fm7z79p6pmxd5k"
