apiVersion: v1
kind: Secret
metadata:
  name: rancher-api-credentials
  namespace: default
type: Opaque
stringData:
  RANCHER_TOKEN: "token-pzplq:kfv7s8nnp2wkw8lxqm49sl6pcbjw7rqhhkdt5b67kmzrrgf944d99k"
